ALTER TABLE incidents ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS item_name TEXT;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS catalog_id TEXT;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS photos JSONB DEFAULT '[]';
