ALTER TABLE manuals ADD COLUMN IF NOT EXISTS course TEXT;
ALTER TABLE manuals ADD COLUMN IF NOT EXISTS lab_room TEXT;
ALTER TABLE manuals ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Active';
ALTER TABLE manuals ADD COLUMN IF NOT EXISTS file_size TEXT;
ALTER TABLE manuals ADD COLUMN IF NOT EXISTS file_type TEXT;
ALTER TABLE manuals ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;
