export const SUBJECTS = [
  "Computer Programming 1",
  "Computer Programming 2",
  "Data Structures and Algorithms",
  "Database Management Systems",
  "Web Development",
  "Computer Networking",
  "Operating Systems",
  "Software Engineering",
  "Embedded Systems",
  "Digital Electronics",
  "Microprocessor Systems",
  "Computer Architecture",
  "Object-Oriented Programming",
  "Systems Analysis and Design",
  "Information Security",
  "Electronics Circuits",
  "Signal Processing",
  "Control Systems",
  "Power Electronics",
  "Microcontrollers",
];
